### ISSUE TITLE
Assign workspaces to monitors

### ISSUE THREAD

**Issue by Big-Tree** [infokiller/i3-workspace-groups#43] opened 2020-12-08 13:12 UTC
Hi, i3-workspace-groups is exactly what I was looking for!  However the following lines in my i3 config file no longer work.  If I am in workspace 1 on my left monitor and then switch to workspace 6, the new workspace will be created on the left monitor instead of the right.

```
# Monitors:                                                                     
set $left_mon DP-4                                                              
set $right_mon DP-2   

# Variable names of workspaces                                                      
#Left                                                                               
set $wp_1 1                                                                         
set $wp_2 2                                                                         
set $wp_3 3                                                                         
set $wp_4 4                                                                         
set $wp_5 5                                                                         
#Right                                                                              
set $wp_6 6                                                                         
set $wp_7 7                                                                         
set $wp_8 8                                                                         
set $wp_9 9                                                                         
set $wp_10 10                                                                       
                                                                                    
# Set monitor of workspaces 
workspace $wp_3 output $left_mon                                                
workspace $wp_1 output $left_mon                                                
workspace $wp_2 output $left_mon                                                
workspace $wp_4 output $left_mon                                                
workspace $wp_5 output $left_mon                                                
workspace $wp_8 output $right_mon                                               
workspace $wp_6 output $right_mon                                               
workspace $wp_7 output $right_mon                                               
workspace $wp_9 output $right_mon                                               
workspace $wp_10 output $right_mon
```

**Comment by infokiller** [comment] 2020-12-08 18:10
Yup, that's a current limitation, see https://github.com/infokiller/i3-workspace-groups/issues/34
I'm closing this issue since it's a duplicate of the other one

**Closed by infokiller** 2020-12-08 18:10 UTC
