### ISSUE TITLE
Workspace 1 - inconsistent behavior

### ISSUE THREAD

**Issue by tigerjack** [infokiller/i3-workspace-groups#35] opened 2020-09-05 15:20 UTC
Whenever I start i3, workspace number 1 is automatically shown.
However, if I use the usual `$sup + 1` to switch to workspace 1, another workspace with the same number pops up, as clear from the figure.

![image](https://user-images.githubusercontent.com/8199216/92308139-d920db80-ef9b-11ea-9b23-d7495d412562.png)

Those are the relevant lines of the i3 config file.
```
# bindsym $sup+1 workspace 1
set $exec_i3_groups exec --no-startup-id i3-workspace-groups
bindsym $sup+1 $exec_i3_groups workspace-number 1
```

Any clue on what's happening?

EDIT: Of course, without `i3-workspace-groups`, the behaviour is consistent. Also, I know that I'm not using the library at all here. Still, I prefer to use the "normal" behaviour in most cases, while switching to the power of groups only in specific circumstances. 

EDIT2: pip shows that I have version 0.4.6 (latest).

**Comment by infokiller** [comment] 2020-09-06 06:58
`i3-workspace-groups` should work normally when you only use a single group (as if you used vanilla i3).
Can you please the full output of `i3-workspace-groups --log-level debug list-workspaces`?
The issue will likely be fixed if you run `i3-workspace-groups switch-active-group ''` (run it before you have the issue with the duplicate workspace)

**Comment by tigerjack** [comment] 2020-09-09 08:55
> `i3-workspace-groups` should work normally when you only use a single group (as if you used vanilla i3).
Exactly, but unfortunately that's not what's happening for me.
> Can you please the full output of `i3-workspace-groups --log-level debug list-workspaces`?

Here it is. Indeed the two workspaces have different static and dynamic names.
```
2020-09-09 10:51:16,289 DEBUG [i3-workspace-groups:201] Using merged config:
{'icons': {'default_icon': '',
           'delimiter': '',
           'enable': False,
           'enable_all_groups': False,
           'min_duplicates_count': 3,
           'rules': [{'icon': '\ue795',
                      'match': 'kitty|Termite|URxvtc?',
                      'property': 'class'},
                     {'icon': '\ue743',
                      'match': 'Chromium|Chrome',
                      'property': 'class'},
                     {'icon': '\ue745',
                      'match': 'Firefox',
                      'property': 'class'},
                     {'icon': '\uf0ea', 'match': 'copyq', 'property': 'class'},
                     {'icon': '\ue5fe', 'match': 'Ranger', 'property': 'class'},
                     {'icon': '\uf120', 'match': 'Rofi', 'property': 'class'},
                     {'icon': '\ue244', 'match': 'Pqiv', 'property': 'class'},
                     {'icon': '\ue22b', 'match': 'Pinta', 'property': 'class'},
                     {'icon': '\uf008', 'match': '[Mm]pv', 'property': 'class'},
                     {'icon': '嗢', 'match': '[Vv]lc', 'property': 'class'},
                     {'icon': '\uf1c2',
                      'match': '[Ll]ibreoffice-writer',
                      'property': 'class'},
                     {'icon': '\uf1c3',
                      'match': '[Ll]ibreoffice-calc',
                      'property': 'class'},
                     {'icon': '\uf03d', 'match': 'Peek', 'property': 'class'},
                     {'icon': '\ue235',
                      'match': 'ipython',
                      'property': 'class'},
                     {'icon': '\ue235', 'match': 'python', 'property': 'class'},
                     {'icon': '\ue235',
                      'match': 'jupyter-qtconsole',
                      'property': 'class'},
                     {'icon': '\ue7c5', 'match': 'Gvim', 'property': 'class'},
                     {'icon': '\uf013',
                      'match': 'settings',
                      'property': 'class'},
                     {'icon': '聆', 'match': 'slack', 'property': 'class'},
                     {'icon': '\uf725',
                      'match': 'Zathura',
                      'property': 'class'},
                     {'icon': '\ue215',
                      'match': 'Telegram',
                      'property': 'class'},
                     {'icon': '墳',
                      'match': 'Pavucontrol',
                      'property': 'class'}],
           'try_fallback_rules': True},
 'renumber_workspaces': False}
2020-09-09 10:51:16,296 DEBUG [workspace_names.py:251] Workspace 1:​​​​1 parsed as: {'global_number': 1, 'group': '', 'static_name': '', 'dynamic_name': '', 'local_number': 1}
2020-09-09 10:51:16,296 DEBUG [workspace_names.py:251] Workspace 1 parsed as: {'global_number': None, 'group': '', 'static_name': '1', 'dynamic_name': None, 'local_number': None}
2020-09-09 10:51:16,296 DEBUG [workspace_names.py:251] Workspace 2:​​​​2 parsed as: {'global_number': 2, 'group': '', 'static_name': '', 'dynamic_name': '', 'local_number': 2}
2020-09-09 10:51:16,296 DEBUG [workspace_names.py:251] Workspace 10:​​​​10 parsed as: {'global_number': 10, 'group': '', 'static_name': '', 'dynamic_name': '', 'local_number': 10}
2020-09-09 10:51:16,296 INFO [icons.py:47] No icon specified for window with class: "firefox", instance: "Navigator", title: "Workspace 1 - inconsistent behavior · Issue #35 · infokiller/i3-workspace-groups - Mozilla Firefox", name: "Workspace 1 - inconsistent behavior · Issue #35 · infokiller/i3-workspace-groups - Mozilla Firefox"
2020-09-09 10:51:16,297 INFO [icons.py:47] No icon specified for window with class: "firefox", instance: "Navigator", title: "politecnico di milano software - Google Search - Mozilla Firefox", name: "politecnico di milano software - Google Search - Mozilla Firefox"
2020-09-09 10:51:16,297 INFO [icons.py:47] No icon specified for window with class: "Emacs", instance: "emacs", title: "emacs@hp255g6", name: "emacs@hp255g6"
2020-09-09 10:51:16,297 INFO [icons.py:47] No icon specified for window with class: "Zotero", instance: "Navigator", title: "Zotero", name: "Zotero"
2020-09-09 10:51:16,297 INFO [icons.py:47] No icon specified for window with class: "Thunderbird", instance: "Mail", title: "Inbox - Polimi - Mozilla Thunderbird", name: "Inbox - Polimi - Mozilla Thunderbird"
1				1		1:​​​​1	eDP
		1				1	eDP
2				2	4x	2:​​​​2	eDP
10				10		10:​​​​10	eDP
```


> The issue will likely be fixed if you run `i3-workspace-groups switch-active-group ''` (run it before you have the issue with the duplicate workspace)
I'm not sure I understood it correctly. Do you mean, run it every time before launching i3?

**Comment by infokiller** [comment] 2020-09-09 18:31
> > The issue will likely be fixed if you run `i3-workspace-groups switch-active-group ''` (run it before you have the issue with the duplicate workspace)
> 
> I'm not sure I understood it correctly. Do you mean, run it every time before launching i3?

You shouldn't need to run this if your config has the i3-workspace-groups commands as [documented in the README](https://github.com/infokiller/i3-workspace-groups#i3-config).
Did you start i3 with the i3-workspace-groups commands already in the config, or did you only add them after starting i3?

Can you please verify if the issue is fixed if you run `i3-workspace-groups switch-active-group ''` followed by closing one of the duplicate `1` workspaces?

**Comment by tigerjack** [comment] 2020-09-09 18:55
@infokiller yep the configuration for the main commands is pretty much the same.
Also, I can fix the error even without running the command. Indeed, when i3 starts, I am in workspace 1. However, if I don't have any window opened in this workspace and I press `$sup+1`, another workspace 1 opens up and the previous one just disappear.
On the other hand, if some window is opened in the original workspace 1, it does not disappear, but I can access it just using `sup+p` or `$sup+n`.

**Comment by infokiller** [comment] 2020-09-09 19:07
Did using `i3-workspace-groups switch-active-group ''` (and then getting rid of the first workspace) work?
If so, what you can do is add to your i3 config `exec --no-startup-id i3-workspace-groups switch-active-group ''`.
Alternatively, if you are interested in having window icons in your config, you can add `exec --no-startup-id i3-autoname-workspaces`, which will spawn a daemon that automatically adds window icons to the workspace names.

**Comment by tigerjack** [comment] 2020-09-09 21:29
Different scenarios tried:
- Open a terminal inside original workspace 1, go to new workspace 1 using `$sup+1` and open a terminal window, going back to original workspace 1. If I execute the suggested command I obtain this
![image](https://user-images.githubusercontent.com/8199216/92656439-55485580-f2f3-11ea-9443-443e035e580a.png)
Now If I press `$sup+1` I go to the workspace 1:1; the other one is only accessible through `$sup+p`.
- Same as before, but executing the command inside new workspace 1. I obtain the same result, just now the focused workspace is 1 (and not 1:1 as before).
- Open a terminal inside original workspace 1 and execute the suggested command directly there. Now I end up only with the workspace 1:1. If I press `$sup+2` a new workspace is open, called just 2. If I press `$sup+1` I'll go back to workspace 1:1.
- Same as previous, but now I `execute exec --no-startup-id i3-workspace-groups switch-active-group 'a'` (note the `a` in the name). I end up with two workspaces, a:1 and 1:1; the focus is on 1:1. However, if from workspace 1:1 I press `$sup+2`, a new workspace is created named a:2.

I'll try the icon suggestion, but anyway I think that there is some kind of bug somewhere.

**Comment by infokiller** [comment] 2020-09-09 22:12
Thanks for the detailed description!
Just to clarify: the fact you see a workspace named `1:1` is not a bug, it's the intended behavior. If you want to see it only as `1`, you need to add `strip_workspace_numbers yes` to your i3bar config as documented in the README.

What is the buggy behavior here is that you have the `1` workspace in addition to the `1:1` one, instead of only having `1:1`.

But, if you run `i3-workspace-groups switch-active-group ''` after you start i3, without creating any other workspaces and without opening any window, it should work. Can you confirm this?
If that's the case, if you add `exec --no-startup-id i3-workspace-groups switch-active-group ''`, and then work normally, you shouldn't hit that bug.

**Comment by infokiller** [comment] 2020-10-06 01:34
Closing because I can't reproduce, please re-open if you get back to this.

**Closed by infokiller** 2020-10-06 01:34 UTC
Labels: waiting for author
