### ISSUE TITLE
Latest git head: moving a container fails

### ISSUE THREAD

**Issue by jcelerier** [infokiller/i3-workspace-groups#38] opened 2020-09-29 08:09 UTC
Simple repro: 
```
$  i3-workspace-groups move-to-number 2
Traceback (most recent call last):
  File "/usr/bin/i3-workspace-groups", line 263, in <module>
    main()
  File "/usr/bin/i3-workspace-groups", line 227, in main
    controller.move_to_workspace_number(_create_group_context(args),
TypeError: move_to_workspace_number() takes 3 positional arguments but 4 were given
```

**Comment by infokiller** [comment] 2020-09-29 15:40
I'm on latest master and can't reproduce.
It looks like you're actually running it from `/usr/lib` and not the repo?
What is the output of `sha256sum <path to i3-workspace-groups>`?
Please verify it's the same as the master version

**Comment by jcelerier** [comment] 2020-09-29 19:20
Hello,
tried from a fresh git clone (was using the arch -git package), all the same: 

```
 /tmp/i3-workspace-groups/scripts | master#0.4.7-a4 ?1
❯ ./i3-workspace-groups move-to-number 2
Traceback (most recent call last):
  File "./i3-workspace-groups", line 263, in <module>
    main()
  File "./i3-workspace-groups", line 227, in main
    controller.move_to_workspace_number(_create_group_context(args),
TypeError: move_to_workspace_number() takes 3 positional arguments but 4 were given

```

```
$ git log
commit 8386c73659446caafc0eb715b5abdfbb5db15d98 (HEAD -> master, tag: 0.4.7-a4, origin/master, origin/HEAD)

$ sha256sum i3-workspace-groups
ff72c58b79b17129bef5492e8edb127091537d0eeaaa87307690ea1aa9de3c28  i3-workspace-groups
```

**Comment by infokiller** [comment] 2020-09-29 19:47
If you look at the code you will see the error is clearly unrelated:
https://github.com/infokiller/i3-workspace-groups/blob/master/i3wsgroups/controller.py#L243-L246

You probably need to run `pip uninstall i3-workspace-groups` or something because it uses an old file. Or set your `PYTHONPATH` to the project root. Closing now, please re-open if this doesn't fix it and if you can reproduce it in a docker container that I can use to repro.

**Closed by infokiller** 2020-09-29 19:47 UTC
Labels: waiting for author
